services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: oracle
      MINIO_ROOT_PASSWORD: oracleoracle
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  # 버킷 자동 생성(1회 실행)
  minio_init:
    image: minio/mc:latest
    container_name: minio_init
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 oracle oracleoracle; do sleep 1; done;
      mc mb -p local/mlflow || true;
      mc anonymous set download local/mlflow || true;
      echo 'MinIO bucket ready: s3://mlflow';
      "

##volumes:
##  minio_data:
